#!/usr/bin/ruby -w

# Disable Messages
$VERBOSE=false

# Include fileutils
require 'fileutils'
require 'open3'

site = ARGV.first

# Print Banner
puts "## Site Disabler for Bakery Server ##"
puts "Disabling nginx site: #{site}"

# Nginx Config File Path
enablednginxfile = "/etc/nginx/sites-enabled/#{site}"

# Write File
if File.exists?( enablednginxfile )
  File.delete( enablednginxfile )
  system("/etc/init.d/nginx force-reload")
  puts "[ Done! ]"
else
  puts "[ Failed ] Failed Site not enabled"
end
# Finished
